USE [master]
GO

IF DB_ID('MUSICAL_AVANZADA') IS NOT NULL
BEGIN
  DROP DATABASE [MUSICAL_AVANZADA]
END
GO


CREATE DATABASE [MUSICAL_AVANZADA]
GO
USE [MUSICAL_AVANZADA]
GO

CREATE SCHEMA [SCH_MUSICAL_AVANZADA] 


-- Si se trabajara con identity, no se utiliza este apartado de usuarios

CREATE TABLE [SCH_MUSICAL_AVANZADA].[USUARIOS]
(
    [USUARIOS_IDENTIFICACION] NVARCHAR (9) NOT NULL,                               -- LLAVE PRIMARIA
    [NOMBRECOMPLETO] NVARCHAR(200) NOT NULL,
    [GENERO] NVARCHAR(10) NOT NULL, -- Masculino o Femenino
    [CORREOELECTRONICO] NVARCHAR(100) NOT NULL,
    [TIPODETARJETA] NVARCHAR(20) NOT NULL, -- VISA, MASTERCARD, AMERICAN EXPRESS
    [NUMERODETARJETA] NVARCHAR(19) NOT NULL, -- formato 0000-0000-0000-0000
    [CONTRASENA] NVARCHAR(50) NOT NULL,

		 CONSTRAINT [PK_USUARIOS] PRIMARY KEY CLUSTERED
	(
		[USUARIOS_IDENTIFICACION] ASC
	)
)
GO

CREATE TABLE [SCH_MUSICAL_AVANZADA].[GENERO_MUSICAL]
(
   [CODIGO_GENERO] NVARCHAR (20) NOT NULL, -- LLAVE PRIMARIA
   [DESCRIPCION_GENERO] NVARCHAR (300) NOT NULL

   		 CONSTRAINT [PK_GENERO_MUSICAL] PRIMARY KEY CLUSTERED
	(
		[CODIGO_GENERO] ASC
	)
)

CREATE TABLE [SCH_MUSICAL_AVANZADA].[MODULO_CANCIONES]
(
   [CODIGO_CANCION] NVARCHAR(20) NOT NULL,                                 -- LLLAVE PRIMARIA
   [NOMBRE_CANCION] VARCHAR (100)NOT NULL,
   [PRECIO_CANCION] DECIMAL (10,2) NOT NULL,
   [CODIGO_GENERO] NVARCHAR(20) NOT NULL                                    --LLAVE FORANEA

   		 CONSTRAINT [PK_MODULO_CANCIONES] PRIMARY KEY CLUSTERED
	(
		[CODIGO_CANCION] ASC
	)
)

CREATE TABLE [SCH_MUSICAL_AVANZADA].[VENTA_CANCIONES]
( 
	 [NUMERO_FACTURA] NVARCHAR (20)NOT NULL, -- LLAVE PRIMARIA (AUTOMATICAMENTE O MANUAL)
	 [SUBTOTAL] DECIMAL (10,2) NOT NULL,
	 [TOTAL] DECIMAL (10,2) NOT NULL, 
	 [FECHA_COMPRA] DATETIME NOT NULL, --FECHA TIENE QUE OBLIGATORIA
	 [USUARIOS_IDENTIFICACION] NVARCHAR (9) NOT NULL,                            -------------LLave foranea
	 [CODIGO_CANCION] NVARCHAR(20) NOT NULL,                                     -------------LLave foranea

	  		 CONSTRAINT [PK_VENTA_CANCIONES] PRIMARY KEY CLUSTERED
	(
		[CODIGO_CANCION] ASC
	)
)

-------------------------------------------------------------------LLAVES FORANEAS---------------------------------------------------------------------
--MODULO CANCIONES
ALTER TABLE [SCH_MUSICAL_AVANZADA].[MODULO_CANCIONES]
ADD CONSTRAINT [FK_MODULO_CANCIONES_CODIGO_GENERO] FOREIGN KEY ([CODIGO_GENERO])
REFERENCES [SCH_MUSICAL_AVANZADA].[GENERO_MUSICAL]([CODIGO_GENERO])
GO
ALTER TABLE [SCH_MUSICAL_AVANZADA].[MODULO_CANCIONES]
CHECK CONSTRAINT [FK_MODULO_CANCIONES_CODIGO_GENERO]
GO

--VENTA CANCIONES
ALTER TABLE [SCH_MUSICAL_AVANZADA].[VENTA_CANCIONES]
ADD CONSTRAINT [FK_VENTA_CANCIONES_USUARIOS_IDENTIFICACION] FOREIGN KEY ([USUARIOS_IDENTIFICACION])
REFERENCES [SCH_MUSICAL_AVANZADA].[USUARIOS]([USUARIOS_IDENTIFICACION])
GO
ALTER TABLE [SCH_MUSICAL_AVANZADA].[VENTA_CANCIONES]
CHECK CONSTRAINT [FK_VENTA_CANCIONES_USUARIOS_IDENTIFICACION]
GO

ALTER TABLE [SCH_MUSICAL_AVANZADA].[VENTA_CANCIONES]
ADD CONSTRAINT [FK_VENTA_CANCIONES_CODIGO_CANCION] FOREIGN KEY ([CODIGO_CANCION])
REFERENCES [SCH_MUSICAL_AVANZADA].[MODULO_CANCIONES]([CODIGO_CANCION])
GO
ALTER TABLE [SCH_MUSICAL_AVANZADA].[VENTA_CANCIONES]
CHECK CONSTRAINT [FK_VENTA_CANCIONES_CODIGO_CANCION]
GO